######################### default configuration ###############################
baseURL = "https://www.leaderline.com.sa/"
languageCode = "ar"
defaultContentLanguage = "ar"
title = "Leaderline"
theme = "biztrox-hugo"
# post pagination
paginate = 6
# post excerpt
summaryLength = "25"
# disqus short name
disqusShortname = "biztrox" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [''] # desable language from here
enableRobotsTXT = true
[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1

############################# enable raw HTML ##############################
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/magnific-popup.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick-theme.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/animate/animate.css"
 
  
  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/magnific-popup.min.js"
  [[params.plugins.js]]
  URL = "plugins/filterizr/jquery.filterizr.min.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"

#################################### navigation ##################################
[menu]

  # main menu
  [[menu.main]]
  name = "About"
  URL = "about/"
  weight = 1
  
  [[menu.main]]
  name = "Service"
  URL = "service/"
  weight = 2
  
  [[menu.main]]
  name = "Business Management Solutions"
  URL = "service/business_management_solutions/"
  parent = "Service"
  weight = 1
  
  [[menu.main]]
  name = "Compliance"
  URL = "service/compliance/"
  parent = "Service"
  weight = 2
  
  [[menu.main]]
  name = "Gap Analysis and Management Audits"
  URL = "service/gap-analysis-and-mgt-audits/"
  parent = "Service"
  weight = 3
  
  [[menu.main]]
  name = "Knowledge Transfer"
  URL = "service/knowledge-transfer/"
  parent = "Service"
  weight = 4
  
  #[[menu.main]]
  #name = "Blog"
  #URL = "blog"
  #weight = 3
  
  #[[menu.main]]
  #name = "Team"
  #URL = "team"
  #weight = 4
  
  #[[menu.main]]
  #name = "Pricing"
  #URL = "pricing"
  #weight = 5
  
  #[[menu.main]]
  #name = "Contact"
  #URL = "contact"
  #weight = 6

  #[[menu.main]]
  #weight = 7
  #name = "Pages"
  #hasChildren = true

    #[[menu.main]]
    #parent = "Pages"
    #name = "Project"
    #URL = "project"

  # footer menu
  [[menu.footer]]
  name = "Legal"
  URL = "pages/legal/"
  weight = 1
  
  [[menu.footer]]
  name = "Sitemap"
  URL = "sitemap.xml"
  weight = 2
  
  [[menu.footer]]
  name = "Privacy Policy"
  URL = "pages/privacy_policy/"
  weight = 3
  
  [[menu.footer]]
  name = "Terms & Conditions"
  URL = "pages/terms_conditions/"
  weight = 4


########################### default parameters #################################
[params]
contentTypeName = "posts"
themeColor = "blue"
showLastUpdated = false
showLanguageSelector = false
fullWidthTheme = false
centerTheme = false
showMenuItems = 2
logo = "images/logo.svg"
logo_white = "images/logo-footer.png"
mail = "info@lmc.sa"
mobile = "966536203055"
# Meta data
description = "Leaderline offers smart business solutions, including management solutions, compliance consulting, improvement journeys, and knowledge transfer. Our professional team is dedicated to providing excellence, professionalism, and effective communication to exceed client expectations. Contact us for a quote and experience the difference."
author = "Muhannad Habiba"
# contact form
contact_form_action = "https://getform.io/f/c57dc65e-7dfc-4563-a3e2-72190a039d27"
# Google Analitycs
google_analitycs_id = "G-276337H0KN"

# mailchimp subsciption
mailchimp_form_action = "https://gmail.us14.list-manage.com/subscribe/post?u=123dc76f8a7d646b42ac7ce4b&amp;id=98237a24ab&amp;f_id=000d82e0f0"
mailchimp_form_name = "b_123dc76f8a7d646b42ac7ce4b_98237a24ab"

# nav Button
[params.nav_button]
enable = true
link = "contact"

# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif"

############################ google map #####################################
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################ client logo slider #############################

### government Sector logo ###

[[params.clients_logo_slider]]
logo = "images/client-logo/MoMRA- Web- Dark.svg"
link = "https://www.momra.gov.sa/"

[[params.clients_logo_slider]]
logo = "images/client-logo/Elm- Web- Dark.svg"
link = "https://www.elm.sa/"

[[params.clients_logo_slider]]
logo = "images/client-logo/MoF- Web- Dark.svg"
link = "https://mof.gov.sa/"

[[params.clients_logo_slider]]
logo = "images/client-logo/HRSD- Web- Dark.svg"
link = "https://hrsd.gov.sa/"

[[params.clients_logo_slider]]
logo = "images/client-logo/Shaqra- Web- Dark.svg"
link = "https://www.su.edu.sa/"

[[params.clients_logo_slider]]
logo = "images/client-logo/SAMA- Web- Dark.svg"
link = "https://www.sama.gov.sa/"

[[params.clients_logo_slider]]
logo = "images/client-logo/M.Housing- Web- Dark.svg"
link = "https://www.housing.gov.sa/"

[[params.clients_logo_slider]]
logo = "images/client-logo/M.Tourism- Web- Dark.svg"
link = "https://mt.gov.sa/"

[[params.clients_logo_slider]]
logo = "images/client-logo/M.Sport- Web- Dark.svg"
link = "https://www.mos.gov.sa/"

[[params.clients_logo_slider]]
logo = "images/client-logo/saudi-esports- Web- Dark.svg"
link = "https://saudiesports.sa/"

[[params.clients_logo_slider]]
logo = "images/client-logo/Financial Academy- Web- Dark.svg"
link = "https://fa.gov.sa/"

[[params.clients_logo_slider]]
logo = "images/client-logo/KAI.SAU- Web- Dark.svg"
link = "https://kai.ksu.edu.sa/"

[[params.clients_logo_slider]]
logo = "images/client-logo/M.Commerce- Web- Dark.svg"
link = "https://mc.gov.sa/"


### Private Sector logo ###

[[params.clients_logo_slider]]
logo = "images/client-logo/SMEH- Web- Dark.svg"
link = "https://www.smeh.com.sa"




########################### social icon #####################################

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://sa.linkedin.com/company/leaderline-lmc"

[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/LMCSolutionsLLC/"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/Leaderline_lmc/"

[Languages]
  
  ################################### English language #####################################
  [Languages.en]
  languageName = "En"
  languageCode = "en"
  owner = ""
  keywords = ""
  copyright = ""
  menuMore = "Show more"
  readMore = "Read more"
  readOtherPosts = "Read other posts"
  missingContentMessage = "Page not found..."
  missingBackButtonLabel = "Back to home page"
  contentDir = "content/english"
  weight = 2
  home = "Home"

  # footer
  [Languages.en.params.footer]
  content = "Leaderline Management Consultancy &trade;, <br> LMC Solutions LLC &reg;, All rights reserved."

  # subscribe
  subscribe = "Subscribe"
  subscribe_content = "Don't missout on latest updates and news, Subscribe to our newslatters."

  # copyright
  copyright = "Copyright &copy; 2023 Leaderline Management Consultancy"



################################ Arabic language ################################
  [Languages.ar]
  languageName = "Ar"
  languageCode = "ar"
  languagedirection = "rtl"
  title = "ليدرلاين"
  owner = ""
  keywords = ""
  copyright = ""
  menuMore = "عرض المزيد"
  readMore = "قراءة المزيد"
  readOtherPosts = "عرض المزيد من المواضيع"
  missingContentMessage = "الصفحة غير موجودة..."
  missingBackButtonLabel = "العودة الى الصفحة الرئيسية"
  contentDir = "content/arabic"
  weight = 1
  home = "الصفحة الرئيسية"
  
##### navigation AR #####    
  # main menu
  [[Languages.ar.menu.main]]
  name = "نبذة"
  URL = "about/"
  weight = 1
  
  [[Languages.ar.menu.main]]
  name = "خدماتنا"
  URL = "service/"
  weight = 2
  
  [[Languages.ar.menu.main]]
  name = "حلول إدارة الاعمال"
  URL = "service/business_management_solutions/"
  parent = "خدماتنا"
  weight = 1
  
  [[Languages.ar.menu.main]]
  name = "الامتثال"
  URL = "service/compliance/"
  parent = "خدماتنا"
  weight = 2
  
  [[Languages.ar.menu.main]]
  name = "تحليل الفجوة والتدقيق الإداري"
  URL = "service/gap-analysis-and-mgt-audits/"
  parent = "خدماتنا"
  weight = 3
  
  [[Languages.ar.menu.main]]
  name = "نقل المعرفة"
  URL = "service/knowledge-transfer/"
  parent = "خدماتنا"
  weight = 4
  
  # footer menu
  [[Languages.ar.menu.footer]]
  name = "Legal"
  URL = "pages/legal/"
  weight = 1
  
  [[Languages.ar.menu.footer]]
  name = "Sitemap"
  URL = "ar/sitemap.xml"
  weight = 2
  
  [[Languages.ar.menu.footer]]
  name = "Privacy Policy"
  URL = "pages/privacy_policy/"
  weight = 3
  
  [[Languages.ar.menu.footer]]
  name = "Terms & Conditions"
  URL = "pages/terms_conditions/"
  weight = 4  
  
  # footer
  [Languages.ar.params.footer]
  content = "نؤمن بالتميّز . . ."

  # subscribe
  subscribe = "للإشتراك"
  subscribe_content = "لا تفوت آخر التحديثات والأخبار ، اشترك في نشراتنا الإخبارية."

  # copyright
  copyright = "جميع الحقوق محفوظة &copy; 2023 Leaderline Management Consultancy"